import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { MPerson, MFamily, build, run, hasFinitePos } from '../../__tests__/test-helper'

describe('Config options', () => {
  it('maxGreatUncles(0) — no great uncles/aunts', () => {
    const ggp = new MPerson('GreatGrandpa /X/')
    const ggm = new MPerson('GreatGrandma /X/')
    const gp = new MPerson('Grandpa /X/')
    const gm = new MPerson('Grandma /X/')
    const parent = new MPerson('Parent /X/')
    const uncle = new MPerson('Uncle /X/')
    const spouse = new MPerson('Spouse /X/')
    const fulcrumPerson = new MPerson('Fulcrum /X/')
    new MFamily([ggp], [ggm], [gp, uncle])
    new MFamily([gp], [gm], [parent])
    new MFamily([parent], [spouse], [fulcrumPerson])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, gp, gm, ggp, ggm, uncle)
    graph.maxGreatUncles(0)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
    const uncleNode = graph.animator.personNodes.find(n => n.person.getId() === uncle.getId())
    if (uncleNode) assert.ok(uncleNode.mini, 'uncle should be mini with maxGreatUncles(0)')
  })

  it('maxGreatUncles(2) — great uncles included (default)', () => {
    const ggp = new MPerson('GreatGrandpa /Y/')
    const ggm = new MPerson('GreatGrandma /Y/')
    const gp = new MPerson('Grandpa /Y/')
    const gm = new MPerson('Grandma /Y/')
    const parent = new MPerson('Parent /Y/')
    const greatUncle = new MPerson('GreatUncle /Y/')
    const spouse = new MPerson('Spouse /Y/')
    const fulcrumPerson = new MPerson('Fulcrum /Y/')
    new MFamily([ggp], [ggm], [gp, greatUncle])
    new MFamily([gp], [gm], [parent])
    new MFamily([parent], [spouse], [fulcrumPerson])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, gp, gm, ggp, ggm, greatUncle)
    graph.maxGreatUncles(2)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
    const uncleNode = graph.animator.personNodes.find(n => n.person.getId() === greatUncle.getId())
    assert.ok(uncleNode, 'great uncle should be present with maxGreatUncles(2)')
  })

  it('maxUnclesCousins(0) — no uncles/cousins', () => {
    const gp = new MPerson('Grandpa /Z/')
    const gm = new MPerson('Grandma /Z/')
    const parent = new MPerson('Parent /Z/')
    const aunt = new MPerson('Aunt /Z/')
    const uncle = new MPerson('Uncle /Z/')
    const cousin = new MPerson('Cousin /Z/')
    const spouse = new MPerson('Spouse /Z/')
    const fulcrumPerson = new MPerson('Fulcrum /Z/')
    new MFamily([gp], [gm], [parent, aunt])
    new MFamily([uncle], [aunt], [cousin])
    new MFamily([parent], [spouse], [fulcrumPerson])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, gp, gm, aunt, uncle, cousin)
    graph.maxUnclesCousins(0)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
    const cousinNodes = graph.animator.personNodes.filter(n => n.person.getId() === cousin.getId())
    if (cousinNodes.length > 0) {
      for (const cn of cousinNodes) assert.ok(cn.mini, 'cousin should be mini with maxUnclesCousins(0)')
    }
  })

  it('maxUnclesCousins(2) — default includes cousins', () => {
    const gp = new MPerson('Grandpa /W/')
    const gm = new MPerson('Grandma /W/')
    const parent = new MPerson('Parent /W/')
    const aunt = new MPerson('Aunt /W/')
    const uncle = new MPerson('Uncle /W/')
    const cousin = new MPerson('Cousin /W/')
    const spouse = new MPerson('Spouse /W/')
    const fulcrumPerson = new MPerson('Fulcrum /W/')
    new MFamily([gp], [gm], [parent, aunt])
    new MFamily([uncle], [aunt], [cousin])
    new MFamily([parent], [spouse], [fulcrumPerson])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, gp, gm, aunt, uncle, cousin)
    graph.maxUnclesCousins(2)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
  })

  it('setLayoutDirection(true) — left-to-right layout', () => {
    const parent = new MPerson('Parent /L/')
    const spouse = new MPerson('Spouse /L/')
    const fulcrumPerson = new MPerson('Fulcrum /L/')
    const child = new MPerson('Child /L/')
    new MFamily([parent], [spouse], [fulcrumPerson])
    new MFamily([fulcrumPerson], [new MPerson('Partner /L/')], [child])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, child)
    graph.setLayoutDirection(true)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
    assert.ok(graph.getWidth() > 0)
    assert.ok(graph.getHeight() > 0)
    assert.ok(graph.animator.leftToRight, 'animator leftToRight flag should be true')
  })

  it('setLayoutDirection(false) — default top-to-bottom', () => {
    const parent = new MPerson('Parent /T/')
    const spouse = new MPerson('Spouse /T/')
    const fulcrumPerson = new MPerson('Fulcrum /T/')
    const child = new MPerson('Child /T/')
    new MFamily([parent], [spouse], [fulcrumPerson])
    new MFamily([fulcrumPerson], [new MPerson('Partner /T/')], [child])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, child)
    graph.setLayoutDirection(false)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
    assert.equal(graph.animator.leftToRight, false)
  })

  it('displayDuplicateLines(false) — suppresses duplicate lines', () => {
    const grandfather = new MPerson('Grandpa /Q/')
    const grandmother = new MPerson('Grandma /R/')
    const dad = new MPerson('Dad /D/')
    const aunt = new MPerson('Aunt /A/')
    const mom = new MPerson('Mom /M/')
    const uncle = new MPerson('Uncle /U/')
    const fulcrumPerson = new MPerson('Fulcrum /Dup/')
    const spouse = new MPerson('Spouse /Dup/')
    const child = new MPerson('Child /Dup/')
    new MFamily([grandfather], [grandmother], [dad, aunt])
    new MFamily([dad], [mom], [fulcrumPerson])
    new MFamily([uncle], [aunt], [spouse])
    new MFamily([fulcrumPerson], [spouse], [child])
    const { graph, fulcrum } = build(fulcrumPerson, spouse, child, grandfather, grandmother, dad, aunt, mom, uncle)
    graph.displayDuplicateLines(false)
    run(graph, fulcrum)
    assert.equal(graph.getDuplicateLines().length, 0, 'no duplicate lines when disabled')
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
  })

  it('displayNumbers(true) — default produces numbered mini cards', () => {
    const fulcrumPerson = new MPerson('Fulcrum /N/')
    const { graph, fulcrum } = build(fulcrumPerson)
    graph.displayNumbers(true)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
  })

  it('showFamily(n) — switches between multiple spouse families', () => {
    const fulcrumPerson = new MPerson('Fulcrum /M/')
    const spouse1 = new MPerson('Spouse1 /M/')
    const spouse2 = new MPerson('Spouse2 /M/')
    const child1 = new MPerson('Child1 /M/')
    const child2 = new MPerson('Child2 /M/')
    new MFamily([fulcrumPerson], [spouse1], [child1])
    new MFamily([fulcrumPerson], [spouse2], [child2])
    const { graph, fulcrum } = build(fulcrumPerson, spouse1, spouse2, child1, child2)
    graph.showFamily(0)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
    assert.ok(graph.animator.nodes.length >= 3)
  })

  it('maxAncestors(3) and maxDescendants(3) multi-gen deep tree', () => {
    const gggp = new MPerson('GGGP /D/')
    const gggm = new MPerson('GGGM /D/')
    const ggp = new MPerson('GGP /D/')
    const ggm = new MPerson('GGM /D/')
    const gp = new MPerson('GP /D/')
    const gm = new MPerson('GM /D/')
    const parent = new MPerson('Parent /D/')
    const spouse = new MPerson('Spouse /D/')
    const fulcrumPerson = new MPerson('Fulcrum /D/')
    const child = new MPerson('Child /D/')
    const grandchild = new MPerson('Grandchild /D/')
    const ggchild = new MPerson('GGChild /D/')
    new MFamily([gggp], [gggm], [ggp])
    new MFamily([ggp], [ggm], [gp])
    new MFamily([gp], [gm], [parent])
    new MFamily([parent], [spouse], [fulcrumPerson])
    new MFamily([fulcrumPerson], [new MPerson('Partner /D/')], [child])
    new MFamily([child], [new MPerson('Partner2 /D/')], [grandchild])
    new MFamily([grandchild], [new MPerson('Partner3 /D/')], [ggchild])
    const { graph, fulcrum } = build(
      fulcrumPerson,
      parent,
      spouse,
      gp,
      gm,
      ggp,
      ggm,
      gggp,
      gggm,
      child,
      grandchild,
      ggchild,
    )
    graph.maxAncestors(3).maxDescendants(3)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
  })

  it('maxSiblingsNephews(1) — one level of nieces/nephews', () => {
    const gp = new MPerson('GP /S/')
    const gm = new MPerson('GM /S/')
    const parent = new MPerson('Parent /S/')
    const aunt = new MPerson('Aunt /S/')
    const uncle = new MPerson('Uncle /S/')
    const cousin = new MPerson('Cousin /S/')
    const spouse = new MPerson('Spouse /S/')
    const fulcrumPerson = new MPerson('Fulcrum /S/')
    const child = new MPerson('Child /S/')
    new MFamily([gp], [gm], [parent, aunt])
    new MFamily([uncle], [aunt], [cousin])
    new MFamily([parent], [spouse], [fulcrumPerson])
    new MFamily([fulcrumPerson], [new MPerson('Partner /S/')], [child])
    const { graph, fulcrum } = build(fulcrumPerson, parent, spouse, gp, gm, aunt, uncle, cousin, child)
    graph.maxSiblingsNephews(1)
    run(graph, fulcrum)
    for (const n of graph.animator.nodes) assert.ok(hasFinitePos(n))
  })
})
